# socket 连接地址，用于生成二维码
socket_urls: 
  - ws://www.kcm-nixi.cn:35678
  - ws://192.168.31.247:5678
# 监听的ip
host: 0.0.0.0
# 监听的端口号
port: 5678
#osc 服务ip
osc_host: 127.0.0.1
# vrchat的osc端口号
osc_port: 9001
# 归一化参数
min_original: 0.2
max_original: 10
#频率曲线参数
frequency_constant_p: 50
frequency_constant_a: 0
frequency_constant_b: 0